name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # This hides the warning

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium webdriver-manager

      - name: Run wake up script
        run: python wake_up.py
